#!/bin/bash

read -e -p "Введите путь к директории: " path
if [ -d "$path" ]
then
    for size in $(LC_ALL=C stat -c '%F %s' "$1"/* | cut -d ' ' -f 3); do
    sum_size=0
    count=0
    let sum_size=$sum_size+$size
    let count=$count+1
  done
  echo "Средний размер файлов $(($sum_size/$count))"
else
    echo "Путь не существует"
fi
