#!/bin/bash

echo -n "Введите имя файла: "
read TIPE

echo -n "Ваш тип файла $TIPE "

case $TIPE in

  jpg | gif | png)
    echo -n "image"
    ;;

  mp3 | wav)
    echo -n "audio"
    ;;

  txt | doc)
    echo -n "text"
    ;;

  *)
    echo -n "unknown"
    ;;
esac
