#!/bin/bash

echo -n "Введите имя файла: "
read TIPE

echo -n "Ваш тип файла $TIPE "

case $NAME in

  *.jpg | *.gif | *.png )
    echo -n "Картинка"
    ;;

  *.mp3 | *.wav )
    echo -n "Звук"
    ;;

  *.txt | *.doc )
    echo -n "Текст"
    ;;

  * )
    echo -n "Неизвестно"
    ;;
esac
